#!/bin/bash
# DNS Filter - Complete Uninstaller
# Removes everything and restores original DNS settings
# Run: sudo bash uninstall.sh

set -e

# ══════════════════════════════════════════════════════════════════
#  Colors & UI
# ══════════════════════════════════════════════════════════════════
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

ok()    { echo -e "${GREEN}✓${NC} $1"; }
err()   { echo -e "${RED}✗${NC} $1"; }
info()  { echo -e "${YELLOW}→${NC} $1"; }
warn()  { echo -e "${YELLOW}!${NC} $1"; }
title() { echo -e "${CYAN}${BOLD}$1${NC}"; }

banner() {
    clear
    echo -e "${RED}"
    cat << 'BANNER'
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║        DNS CONTENT FILTER - UNINSTALLER                  ║
║                                                           ║
║              Complete Removal & DNS Restore              ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝
BANNER
    echo -e "${NC}"
}

# ══════════════════════════════════════════════════════════════════
#  Checks
# ══════════════════════════════════════════════════════════════════

check_root() {
    if [ "$EUID" -ne 0 ]; then
        err "This script must be run as root"
        echo "  Run: sudo bash $0"
        exit 1
    fi
}

# ══════════════════════════════════════════════════════════════════
#  Uninstall Steps
# ══════════════════════════════════════════════════════════════════

stop_service() {
    title "Stopping DNS Filter service..."
    
    if systemctl is-active dns-filter >/dev/null 2>&1; then
        systemctl stop dns-filter >/dev/null 2>&1
        ok "Service stopped"
    else
        info "Service not running"
    fi
}

disable_service() {
    title "Disabling DNS Filter service..."
    
    if systemctl is-enabled dns-filter >/dev/null 2>&1; then
        systemctl disable dns-filter >/dev/null 2>&1
        ok "Service disabled"
    else
        info "Service not enabled"
    fi
}

remove_service() {
    title "Removing systemd service..."
    
    if [ -f /etc/systemd/system/dns-filter.service ]; then
        rm -f /etc/systemd/system/dns-filter.service
        systemctl daemon-reload
        ok "Service file removed"
    else
        info "Service file not found"
    fi
}

restore_dns() {
    title "Restoring DNS settings..."
    
    # Detect DNS configuration method
    if command -v nmcli >/dev/null 2>&1 && systemctl is-active NetworkManager >/dev/null 2>&1; then
        restore_dns_networkmanager
    else
        restore_dns_resolvconf
    fi
}

restore_dns_networkmanager() {
    info "Detected NetworkManager"
    
    # Get active connection
    local conn=$(nmcli -t -f NAME,DEVICE connection show --active | head -1 | cut -d: -f1)
    
    if [ -z "$conn" ]; then
        warn "No active connection found"
        return 1
    fi
    
    info "Active connection: $conn"
    info "Restoring automatic DNS..."
    
    # Clear DNS settings
    nmcli connection modify "$conn" ipv4.dns "" >/dev/null 2>&1
    nmcli connection modify "$conn" ipv4.ignore-auto-dns no >/dev/null 2>&1
    nmcli connection modify "$conn" ipv6.dns "" >/dev/null 2>&1
    nmcli connection modify "$conn" ipv6.ignore-auto-dns no >/dev/null 2>&1
    
    # Restart connection
    info "Restarting network connection..."
    nmcli connection down "$conn" >/dev/null 2>&1
    sleep 1
    nmcli connection up "$conn" >/dev/null 2>&1
    
    ok "DNS restored to automatic (DHCP)"
}

restore_dns_resolvconf() {
    info "Restoring resolv.conf"
    
    # Make mutable
    chattr -i /etc/resolv.conf 2>/dev/null || true
    
    # Restore backup if exists
    if [ -f /etc/resolv.conf.backup ]; then
        cp /etc/resolv.conf.backup /etc/resolv.conf
        ok "Restored from backup"
    else
        # Create default
        cat > /etc/resolv.conf << 'EOF'
# Generated by uninstaller
nameserver 8.8.8.8
nameserver 1.1.1.1
EOF
        warn "No backup found, using Google DNS (8.8.8.8)"
    fi
    
    # Remove immutable flag
    chattr -i /etc/resolv.conf 2>/dev/null || true
}

remove_cli() {
    title "Removing CLI tool..."
    
    if [ -L /usr/local/bin/dns-cli ]; then
        rm -f /usr/local/bin/dns-cli
        ok "Removed /usr/local/bin/dns-cli"
    fi
    
    if [ -L /usr/local/bin/dns-filter-cli ]; then
        rm -f /usr/local/bin/dns-filter-cli
        ok "Removed /usr/local/bin/dns-filter-cli"
    fi
    
    if [ ! -L /usr/local/bin/dns-cli ] && [ ! -L /usr/local/bin/dns-filter-cli ]; then
        info "CLI not found in /usr/local/bin"
    fi
}

remove_installation() {
    title "Removing installation directory..."
    
    local INSTALL_DIR="/opt/dns-filter"
    
    if [ -d "$INSTALL_DIR" ]; then
        # Ask about data
        echo ""
        echo -e "${YELLOW}Found installation at: $INSTALL_DIR${NC}"
        du -sh "$INSTALL_DIR" 2>/dev/null || true
        echo ""
        
        read -p "Remove all data including logs and blocklists? [y/N] " -n 1 -r
        echo
        
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            rm -rf "$INSTALL_DIR"
            ok "Removed $INSTALL_DIR"
        else
            info "Keeping installation directory"
            warn "To remove manually later: sudo rm -rf $INSTALL_DIR"
        fi
    else
        info "Installation directory not found"
    fi
}

remove_history() {
    title "Cleaning up..."
    
    # Remove CLI history
    if [ -f "$HOME/.dns-cli_history" ]; then
        rm -f "$HOME/.dns-cli_history"
        ok "Removed CLI history"
    fi
    
    # Find and remove user histories
    for home in /home/*; do
        if [ -f "$home/.dns-cli_history" ]; then
            rm -f "$home/.dns-cli_history"
            ok "Removed CLI history for $(basename $home)"
        fi
    done
}

verify_removal() {
    title "Verifying removal..."
    
    local issues=0
    
    # Check service
    if systemctl list-unit-files | grep -q dns-filter; then
        warn "Service still exists"
        ((issues++))
    else
        ok "Service removed"
    fi
    
    # Check port 53
    if lsof -i :53 >/dev/null 2>&1; then
        local process=$(lsof -i :53 -t | head -1)
        local pname=$(ps -p $process -o comm= 2>/dev/null)
        if [ "$pname" = "dns-filter" ]; then
            warn "DNS Filter still running on port 53"
            ((issues++))
        else
            ok "Port 53 not used by DNS Filter"
        fi
    else
        ok "Port 53 free"
    fi
    
    # Check DNS
    local current_dns=$(cat /etc/resolv.conf | grep "^nameserver" | head -1 | awk '{print $2}')
    if [ "$current_dns" = "127.0.0.1" ]; then
        warn "DNS still set to 127.0.0.1"
        echo "  Run: nmcli connection modify <connection> ipv4.dns \"\""
        ((issues++))
    else
        ok "DNS not pointing to 127.0.0.1"
    fi
    
    # Check installation dir
    if [ -d "/opt/dns-filter" ]; then
        info "Installation directory still exists (kept by user)"
    else
        ok "Installation directory removed"
    fi
    
    return $issues
}

# ══════════════════════════════════════════════════════════════════
#  Summary
# ══════════════════════════════════════════════════════════════════

show_summary() {
    echo ""
    echo -e "${GREEN}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}${BOLD}║                                                           ║${NC}"
    echo -e "${GREEN}${BOLD}║          UNINSTALLATION COMPLETE! ✓                      ║${NC}"
    echo -e "${GREEN}${BOLD}║                                                           ║${NC}"
    echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    echo -e "${CYAN}What was removed:${NC}"
    echo "  ✓ DNS Filter service"
    echo "  ✓ Systemd service file"
    echo "  ✓ DNS configuration restored"
    echo "  ✓ CLI tools removed"
    echo "  ✓ History files cleaned"
    echo ""
    
    if [ -d "/opt/dns-filter" ]; then
        echo -e "${YELLOW}Note:${NC} Installation directory kept: /opt/dns-filter"
        echo "      Remove manually: sudo rm -rf /opt/dns-filter"
        echo ""
    fi
    
    echo -e "${CYAN}DNS Status:${NC}"
    echo -n "  Current DNS: "
    cat /etc/resolv.conf | grep "^nameserver" | head -1 | awk '{print $2}'
    echo ""
    
    echo -e "${GREEN}Your system is back to normal configuration.${NC}"
    echo ""
}

show_summary_with_issues() {
    echo ""
    echo -e "${YELLOW}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${YELLOW}${BOLD}║                                                           ║${NC}"
    echo -e "${YELLOW}${BOLD}║      UNINSTALLATION COMPLETE (WITH WARNINGS)             ║${NC}"
    echo -e "${YELLOW}${BOLD}║                                                           ║${NC}"
    echo -e "${YELLOW}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    echo -e "${YELLOW}Some issues detected. Review the warnings above.${NC}"
    echo ""
    
    echo -e "${CYAN}Manual cleanup if needed:${NC}"
    echo "  sudo systemctl stop dns-filter"
    echo "  sudo rm -rf /opt/dns-filter"
    echo "  sudo rm -f /etc/systemd/system/dns-filter.service"
    echo "  sudo systemctl daemon-reload"
    echo ""
}

# ══════════════════════════════════════════════════════════════════
#  Main
# ══════════════════════════════════════════════════════════════════

main() {
    banner
    
    echo -e "${YELLOW}This will completely remove DNS Filter:${NC}"
    echo "  • Stop and disable service"
    echo "  • Remove systemd service file"
    echo "  • Restore original DNS settings"
    echo "  • Remove CLI tools"
    echo "  • Clean up configuration"
    echo "  • Remove installation directory (optional)"
    echo ""
    
    read -p "Continue with uninstallation? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Uninstallation cancelled"
        exit 0
    fi
    
    echo ""
    
    # Run all steps
    check_root
    
    stop_service
    disable_service
    remove_service
    
    echo ""
    restore_dns
    
    echo ""
    remove_cli
    remove_installation
    remove_history
    
    echo ""
    if verify_removal; then
        show_summary
    else
        show_summary_with_issues
    fi
}

# Run
main "$@"